from __future__ import annotations

import logging
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Protocol

from app.utils.log_parser import LinuxAuthLogParser, ParsedLogEvent

# Known IP locations for PoC impossible travel detection
KNOWN_IP_LOCATIONS: dict[str, str] = {
    "192.168.1.10": "Bangalore",
    "8.8.8.8": "New York",
    "1.1.1.1": "Sydney",
}

# MITRE ATT&CK mapping for detected rules
MITRE_MAPPING: dict[str, dict[str, str]] = {
    "brute_force_login_attempts": {"id": "T1110", "name": "Brute Force"},
    "impossible_travel": {"id": "T1078", "name": "Valid Accounts"},
}


@dataclass(slots=True, frozen=True)
class DetectionThresholds:
    """Configurable thresholds used by the detection engine."""

    brute_force_threshold: int = 5
    suspicious_ip_threshold: int = 10
    unusual_login_frequency_threshold: int = 5
    privilege_escalation_threshold: int = 1
    window_minutes: int = 5
    max_risk_score: int = 100


@dataclass(slots=True)
class ThreatAlert:
    """Structured alert generated by the threat detection engine."""

    threat_type: str
    severity: str
    risk_score: int

    mitre_technique_id: str = "T0000"
    mitre_technique_name: str = "Unknown"

    description: str = ""

    source_ip: str | None = None
    username: str | None = None

    status: str = "OPEN"

    evidence: dict[str, Any] = field(default_factory=dict)

    generated_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "threat_type": self.threat_type,
            "severity": self.severity,
            "risk_score": self.risk_score,
            "mitre_technique_id": self.mitre_technique_id,
            "mitre_technique_name": self.mitre_technique_name,
            "status": self.status,
            "description": self.description,
            "source_ip": self.source_ip,
            "username": self.username,
            "evidence": self.evidence,
            "generated_at": self.generated_at.isoformat(),
            "metadata": self.metadata,
        }

    def to_alert_record(self) -> dict[str, Any]:
        return {
            "threat_type": self.threat_type,
            "severity": self.severity,
            "source_ip": self.source_ip or "unknown",
            "log_message": self.description,
            "risk_score": self.risk_score,
            "mitre_technique_id": self.mitre_technique_id,
            "mitre_technique_name": self.mitre_technique_name,
            "status": self.status,
            "metadata": self.metadata,
        }


@dataclass(slots=True)
class DetectionReport:
    """Summary object returned after evaluating a batch of log lines."""

    alerts: list[ThreatAlert]
    processed_events: int
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def total_alerts(self) -> int:
        return len(self.alerts)

    @property
    def summary(self) -> dict[str, Any]:
        counts = Counter(alert.threat_type for alert in self.alerts)
        return {
            "processed_events": self.processed_events,
            "total_alerts": self.total_alerts,
            "alert_counts": dict(counts),
            "generated_at": self.generated_at.isoformat(),
        }

    def to_dict(self) -> dict[str, Any]:
        return {
            "processed_events": self.processed_events,
            "generated_at": self.generated_at.isoformat(),
            "total_alerts": self.total_alerts,
            "summary": self.summary,
            "alerts": [alert.to_dict() for alert in self.alerts],
        }


class DetectionRule(Protocol):
    """Protocol for modular threat detection rules."""

    def evaluate(self, events: list[ParsedLogEvent], thresholds: DetectionThresholds) -> list[ThreatAlert]:
        ...


class BruteForceLoginRule:
    """Detect repeated failed authentication attempts from the same source IP."""

    name = "brute_force_login_attempts"

    def evaluate(self, events: list[ParsedLogEvent], thresholds: DetectionThresholds) -> list[ThreatAlert]:
        counts: Counter[str] = Counter()
        samples: defaultdict[str, list[ParsedLogEvent]] = defaultdict(list)

        for event in events:
            if event.event_type == "failed_ssh_login" and event.source_ip:
                counts[event.source_ip] += 1
                samples[event.source_ip].append(event)

        alerts: list[ThreatAlert] = []
        for source_ip, count in counts.items():
            if count < thresholds.brute_force_threshold:
                continue
            risk_score = min(
                thresholds.max_risk_score,
                35 + (count - thresholds.brute_force_threshold + 1) * 12,
            )
            severity = _classify_severity(risk_score)
            username = samples[source_ip][0].username
            alert = ThreatAlert(
                threat_type=self.name,
                severity=severity,
                risk_score=risk_score,
                mitre_technique_id=MITRE_MAPPING.get(self.name, {}).get("id", "T1110"),
                mitre_technique_name=MITRE_MAPPING.get(self.name, {}).get("name", "Brute Force"),
                description=(
                    f"Repeated failed login attempts detected from source IP {source_ip}. "
                    f"{count} failures observed in the configured detection window."
                ),
                source_ip=source_ip,
                username=username,
                evidence={
                    "failed_attempts": count,
                    "threshold": thresholds.brute_force_threshold,
                    "sample_events": [
                        {
                            "raw_message": sample.raw_message,
                            "username": sample.username,
                            "source_ip": sample.source_ip,
                        }
                        for sample in samples[source_ip][:3]
                    ],
                },
                metadata={
                    "rule": self.name,
                    "window_minutes": thresholds.window_minutes,
                },
            )
            alerts.append(alert)
        return alerts


class SuspiciousIPAccessRule:
    """Detect repeated suspicious access from a source IP over a rolling window."""

    name = "repeated_suspicious_ip_access"

    def evaluate(self, events: list[ParsedLogEvent], thresholds: DetectionThresholds) -> list[ThreatAlert]:
        counts: Counter[str] = Counter()
        samples: defaultdict[str, list[ParsedLogEvent]] = defaultdict(list)

        for event in events:
            if event.source_ip:
                if event.event_type in {"failed_ssh_login", "invalid_user", "successful_ssh_login"}:
                    counts[event.source_ip] += 1
                    samples[event.source_ip].append(event)

        alerts: list[ThreatAlert] = []
        for source_ip, count in counts.items():
            if count < thresholds.suspicious_ip_threshold:
                continue
            risk_score = min(thresholds.max_risk_score, 25 + count * 4)
            severity = _classify_severity(risk_score)
            alert = ThreatAlert(
                threat_type=self.name,
                severity=severity,
                risk_score=risk_score,
                mitre_technique_id=MITRE_MAPPING.get(self.name, {}).get("id", "T1110"),
                mitre_technique_name=MITRE_MAPPING.get(self.name, {}).get("name", "Brute Force"),
                description=(
                    f"Repeated suspicious access from IP {source_ip} detected. "
                    f"{count} authentication-related events observed."
                ),
                source_ip=source_ip,
                username=samples[source_ip][0].username,
                evidence={
                    "event_count": count,
                    "threshold": thresholds.suspicious_ip_threshold,
                    "event_types": [event.event_type for event in samples[source_ip][:5]],
                },
                metadata={
                    "rule": self.name,
                    "window_minutes": thresholds.window_minutes,
                },
            )
            alerts.append(alert)
        return alerts


class UnusualLoginFrequencyRule:
    """Detect unusual login frequency for a user over the configured window."""

    name = "unusual_login_frequency"

    def evaluate(self, events: list[ParsedLogEvent], thresholds: DetectionThresholds) -> list[ThreatAlert]:
        counts: Counter[str] = Counter()
        samples: defaultdict[str, list[ParsedLogEvent]] = defaultdict(list)

        for event in events:
            if event.event_type == "successful_ssh_login" and event.username:
                counts[event.username] += 1
                samples[event.username].append(event)

        alerts: list[ThreatAlert] = []
        for username, count in counts.items():
            if count < thresholds.unusual_login_frequency_threshold:
                continue
            risk_score = min(thresholds.max_risk_score, 30 + (count - thresholds.unusual_login_frequency_threshold + 1) * 8)
            severity = _classify_severity(risk_score)
            alert = ThreatAlert(
                threat_type=self.name,
                severity=severity,
                risk_score=risk_score,
                mitre_technique_id=MITRE_MAPPING.get(self.name, {}).get("id", "T1078"),
                mitre_technique_name=MITRE_MAPPING.get(self.name, {}).get("name", "Valid Accounts"),
                description=(
                    f"Unusual login frequency observed for user {username}. "
                    f"{count} successful logins detected in the configured window."
                ),
                username=username,
                source_ip=samples[username][0].source_ip,
                evidence={
                    "successful_logins": count,
                    "threshold": thresholds.unusual_login_frequency_threshold,
                },
                metadata={
                    "rule": self.name,
                    "window_minutes": thresholds.window_minutes,
                },
            )
            alerts.append(alert)
        return alerts


class PotentialPrivilegeEscalationRule:
    """Detect potential privilege escalation events such as sudo commands."""

    name = "potential_privilege_escalation"

    def evaluate(self, events: list[ParsedLogEvent], thresholds: DetectionThresholds) -> list[ThreatAlert]:
        escalations = [event for event in events if event.event_type == "sudo_privilege_escalation"]
        alerts: list[ThreatAlert] = []

        for event in escalations:
            if event.username is None and thresholds.privilege_escalation_threshold > 1:
                continue
            target_user = event.details.get("target_user")
            risk_score = min(thresholds.max_risk_score, 75)
            if target_user and str(target_user).lower() in {"root", "administrator"}:
                risk_score = min(thresholds.max_risk_score, 90)
            severity = _classify_severity(risk_score)
            alert = ThreatAlert(
                threat_type=self.name,
                severity=severity,
                risk_score=risk_score,
                mitre_technique_id=MITRE_MAPPING.get(self.name, {}).get("id", "T1078"),
                mitre_technique_name=MITRE_MAPPING.get(self.name, {}).get("name", "Valid Accounts"),
                description=(
                    f"Potential privilege escalation detected for user {event.username or 'unknown'} "
                    f"using command context {event.details.get('command') or 'unknown'}."
                ),
                source_ip=event.source_ip,
                username=event.username,
                evidence={
                    "event_type": event.event_type,
                    "target_user": target_user,
                    "command": event.details.get("command"),
                    "tty": event.details.get("tty"),
                },
                metadata={
                    "rule": self.name,
                    "target_user": target_user,
                    "window_minutes": thresholds.window_minutes,
                },
            )
            alerts.append(alert)

        return alerts


class ImpossibleTravelRule:
    """Detect activity from multiple geographically distant locations in the same upload."""

    name = "impossible_travel"

    def evaluate(self, events: list[ParsedLogEvent], thresholds: DetectionThresholds) -> list[ThreatAlert]:
        # Map resolved location -> list of events
        locations: dict[str, list[ParsedLogEvent]] = defaultdict(list)

        for event in events:
            if not event.source_ip:
                continue
            loc = KNOWN_IP_LOCATIONS.get(event.source_ip)
            if loc:
                locations[loc].append(event)

        if len(locations) < 2:
            return []

        distinct_locations = list(locations.keys())
        # Build description
        locations_str = " and ".join(distinct_locations[:2]) if len(distinct_locations) == 2 else ", ".join(distinct_locations)
        description = (
            f"User activity observed from {locations_str} within a short observation window."
        )

        # pick a representative source_ip (first event)
        representative_ip = None
        sample_events = []
        for loc_events in locations.values():
            if loc_events:
                if representative_ip is None:
                    representative_ip = loc_events[0].source_ip
                sample_events.append({
                    "raw_message": loc_events[0].raw_message,
                    "username": loc_events[0].username,
                    "source_ip": loc_events[0].source_ip,
                    "location": KNOWN_IP_LOCATIONS.get(loc_events[0].source_ip),
                })

        alert = ThreatAlert(
            threat_type=self.name,
            severity="high",
            risk_score=85,
            mitre_technique_id=MITRE_MAPPING.get(self.name, {}).get("id", "T1078"),
            mitre_technique_name=MITRE_MAPPING.get(self.name, {}).get("name", "Valid Accounts"),
            description=description,
            source_ip=representative_ip,
            evidence={
                "locations": distinct_locations,
                "sample_events": sample_events,
            },
            metadata={
                "rule": self.name,
                "window_minutes": thresholds.window_minutes,
            },
        )

        return [alert]


class ThreatDetectionEngine:
    """Rule-based infrastructure threat detection engine."""

    def __init__(
        self,
        thresholds: DetectionThresholds | None = None,
        rules: list[DetectionRule] | None = None,
        logger: logging.Logger | None = None,
    ) -> None:
        self.thresholds = thresholds or DetectionThresholds()
        self.rules = rules or [
            BruteForceLoginRule(),
            ImpossibleTravelRule(),
            SuspiciousIPAccessRule(),
            UnusualLoginFrequencyRule(),
            PotentialPrivilegeEscalationRule(),
        ]
        self._logger = logger or logging.getLogger(__name__)
        self._parser = LinuxAuthLogParser()

    def evaluate_logs(self, raw_lines: list[str]) -> DetectionReport:
        """Evaluate a batch of raw log lines and return a detection report."""

        parsed_events = [self._parser.parse(line) for line in raw_lines]
        alerts: list[ThreatAlert] = []

        for rule in self.rules:
            rule_alerts = rule.evaluate(parsed_events, self.thresholds)
            alerts.extend(rule_alerts)
            for alert in rule_alerts:
                self._log_alert(alert)

        report = DetectionReport(alerts=self._sort_alerts(alerts), processed_events=len(parsed_events))
        self._logger.info(
            "Threat detection analysis completed",
            extra={
                "summary": report.summary,
            },
        )
        return report

    def _sort_alerts(self, alerts: list[ThreatAlert]) -> list[ThreatAlert]:
        return sorted(alerts, key=lambda alert: (-alert.risk_score, alert.threat_type))

    def _log_alert(self, alert: ThreatAlert) -> None:
        structured_payload = alert.to_dict()
        self._logger.warning(
            "Threat detection alert generated",
            extra={"alert": structured_payload},
        )


def _classify_severity(risk_score: int) -> str:
    if risk_score >= 80:
        return "critical"
    if risk_score >= 60:
        return "high"
    if risk_score >= 40:
        return "medium"
    return "low"


threat_detection_engine = ThreatDetectionEngine()


__all__ = [
    "BruteForceLoginRule",
    "DetectionReport",
    "DetectionRule",
    "DetectionThresholds",
    "PotentialPrivilegeEscalationRule",
    "SuspiciousIPAccessRule",
    "ThreatAlert",
    "ThreatDetectionEngine",
    "ThreatDetectionEngine",
    "UnusualLoginFrequencyRule",
    "threat_detection_engine",
]
